# Generated by Django 5.2.3 on 2025-07-03 08:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Disk",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number",
                    models.CharField(max_length=255, verbose_name="Номер диска"),
                ),
                ("copyes", models.IntegerField(verbose_name="Количество копий")),
                ("content", models.TextField(verbose_name="Содержание")),
            ],
            options={
                "verbose_name": "Диск",
                "verbose_name_plural": "Диски",
                "ordering": ["number"],
            },
        ),
        migrations.CreateModel(
            name="Organizations",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField(verbose_name="Название организации")),
            ],
            options={
                "verbose_name": "Организация",
                "verbose_name_plural": "Организации",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="topics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField(verbose_name="Тема документа")),
            ],
            options={
                "verbose_name": "Темы документа",
                "verbose_name_plural": "Темы документов",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="IncomingLetter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number",
                    models.CharField(
                        help_text="(обязательное) Номер письма в нашей организации",
                        max_length=255,
                        verbose_name="Номер письма",
                    ),
                ),
                (
                    "self_date",
                    models.DateField(
                        help_text="(обязательное) Дата письма в нашей организации",
                        verbose_name="Дата письма",
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        help_text="(обязательное)", verbose_name="Содержание"
                    ),
                ),
                (
                    "sender_number",
                    models.CharField(verbose_name="Номер письма отправителя"),
                ),
                (
                    "sender_date",
                    models.DateField(
                        help_text="(обязательное) Дата отправителя",
                        verbose_name="Дата письма",
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        help_text="Создается автоматически",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_authors",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Автор записи",
                    ),
                ),
                (
                    "workers",
                    models.ManyToManyField(
                        blank=True,
                        help_text="(не обязательное) Добавьте исполнителей письма",
                        related_name="assigned_letters",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Исполнители",
                    ),
                ),
                (
                    "addressee",
                    models.ForeignKey(
                        help_text="(обязательное)",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="doc.organizations",
                        verbose_name="Адресат",
                    ),
                ),
            ],
            options={
                "verbose_name": "Входящее письмо",
                "verbose_name_plural": "Входящие письма",
            },
        ),
        migrations.CreateModel(
            name="OutgoingLetter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number",
                    models.CharField(
                        help_text="(обязательное) Номер письма в нашей организации",
                        max_length=255,
                        verbose_name="Номер письма",
                    ),
                ),
                (
                    "self_date",
                    models.DateField(
                        help_text="(обязательное) Дата письма в нашей организации",
                        verbose_name="Дата письма",
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        help_text="(обязательное)", verbose_name="Содержание"
                    ),
                ),
                (
                    "outgoing_date",
                    models.DateField(
                        help_text="(обязательное) Добавьте от какого числа письмо",
                        verbose_name="Дата отправки",
                    ),
                ),
                (
                    "addressee",
                    models.ManyToManyField(
                        blank=True,
                        help_text="(обязательное)",
                        to="doc.organizations",
                        verbose_name="Адресаты",
                    ),
                ),
                (
                    "answer_by",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="doc.incomingletter",
                        verbose_name="Ответ на вх. письмо",
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        help_text="Создается автоматически",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_authors",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Автор записи",
                    ),
                ),
                (
                    "disk",
                    models.ManyToManyField(
                        blank=True,
                        help_text="(не обязательное) Добавьте новый диск для записи через LPBurn.",
                        to="doc.disk",
                        verbose_name="Диск",
                    ),
                ),
                (
                    "topic",
                    models.ManyToManyField(
                        to="doc.topics", verbose_name="Тема документа"
                    ),
                ),
            ],
            options={
                "verbose_name": "Исходящее письмо",
                "verbose_name_plural": "Исходящие письма",
            },
        ),
        migrations.AddField(
            model_name="incomingletter",
            name="answer_by",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="doc.outgoingletter",
                verbose_name="Ответ на исх. письмо",
            ),
        ),
        migrations.CreateModel(
            name="Memo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number",
                    models.CharField(
                        help_text="(обязательное) Номер письма в нашей организации",
                        max_length=255,
                        verbose_name="Номер письма",
                    ),
                ),
                (
                    "self_date",
                    models.DateField(
                        help_text="(обязательное) Дата письма в нашей организации",
                        verbose_name="Дата письма",
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        help_text="(обязательное)", verbose_name="Содержание"
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        help_text="Создается автоматически",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_authors",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Автор записи",
                    ),
                ),
                (
                    "addressee",
                    models.ManyToManyField(
                        blank=True,
                        help_text="(обязательное)",
                        to="doc.organizations",
                        verbose_name="Адресаты",
                    ),
                ),
                (
                    "topic",
                    models.ManyToManyField(
                        to="doc.topics", verbose_name="Тема документа"
                    ),
                ),
            ],
            options={
                "verbose_name": "Служебная записка",
                "verbose_name_plural": "Служебные записки",
            },
        ),
        migrations.AddField(
            model_name="incomingletter",
            name="topic",
            field=models.ManyToManyField(
                to="doc.topics", verbose_name="Тема документа"
            ),
        ),
        migrations.CreateModel(
            name="Act",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number",
                    models.CharField(
                        help_text="(обязательное) Номер письма в нашей организации",
                        max_length=255,
                        verbose_name="Номер письма",
                    ),
                ),
                (
                    "self_date",
                    models.DateField(
                        help_text="(обязательное) Дата письма в нашей организации",
                        verbose_name="Дата письма",
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        help_text="(обязательное)", verbose_name="Содержание"
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        help_text="Создается автоматически",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_authors",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Автор записи",
                    ),
                ),
                (
                    "topic",
                    models.ManyToManyField(
                        to="doc.topics", verbose_name="Тема документа"
                    ),
                ),
            ],
            options={
                "verbose_name": "Акт",
                "verbose_name_plural": "Акты",
            },
        ),
    ]
