# Generated by Django 5.2.3 on 2025-06-26 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Letter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.TextField(verbose_name="Номер письма")),
                ("content", models.CharField(verbose_name="Информация")),
                ("send_date", models.DateTimeField(verbose_name="Дата отправки")),
            ],
            options={
                "verbose_name": "Письмо",
                "verbose_name_plural": "Письма",
            },
        ),
    ]
