# Generated by Django 5.2.3 on 2025-06-26 13:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doc", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Disk",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number",
                    models.CharField(max_length=255, verbose_name="Номер диска"),
                ),
                ("copyes", models.IntegerField(verbose_name="Количество копий")),
                ("content", models.TextField(verbose_name="Содержание")),
            ],
        ),
        migrations.CreateModel(
            name="Organizations",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField(verbose_name="Название организации")),
            ],
        ),
        migrations.CreateModel(
            name="Type",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(max_length=255, verbose_name="Статус отправки"),
                ),
            ],
        ),
        migrations.AlterModelOptions(
            name="letter",
            options={
                "ordering": ["send_date"],
                "verbose_name": "Письмо",
                "verbose_name_plural": "Письма",
            },
        ),
        migrations.AlterField(
            model_name="letter",
            name="content",
            field=models.TextField(verbose_name="Содержание"),
        ),
        migrations.AlterField(
            model_name="letter",
            name="number",
            field=models.CharField(max_length=255, verbose_name="Номер письма"),
        ),
        migrations.AlterField(
            model_name="letter",
            name="send_date",
            field=models.DateTimeField(auto_now=True, verbose_name="Дата отправки"),
        ),
        migrations.AddField(
            model_name="letter",
            name="disk",
            field=models.OneToOneField(
                help_text="Добавьте диск для записи через LPBurn",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="doc.disk",
                verbose_name="Диск",
            ),
        ),
        migrations.AddField(
            model_name="letter",
            name="addressee",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="doc.organizations",
                verbose_name="Адресаты",
            ),
        ),
        migrations.AddField(
            model_name="letter",
            name="type",
            field=models.ForeignKey(
                default=0,
                help_text="Акт, СЗ, Входящее...",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="letters",
                to="doc.type",
                verbose_name="Тип документа",
            ),
            preserve_default=False,
        ),
    ]
