# Generated by Django 5.2.3 on 2025-07-03 08:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doc", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="act",
            name="author",
            field=models.ForeignKey(
                blank=True,
                help_text="Создается автоматически",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_authors",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Автор записи",
            ),
        ),
        migrations.AlterField(
            model_name="incomingletter",
            name="author",
            field=models.ForeignKey(
                blank=True,
                help_text="Создается автоматически",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_authors",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Автор записи",
            ),
        ),
        migrations.AlterField(
            model_name="memo",
            name="author",
            field=models.ForeignKey(
                blank=True,
                help_text="Создается автоматически",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_authors",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Автор записи",
            ),
        ),
        migrations.AlterField(
            model_name="outgoingletter",
            name="author",
            field=models.ForeignKey(
                blank=True,
                help_text="Создается автоматически",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_authors",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Автор записи",
            ),
        ),
    ]
