# Generated by Django 5.2.3 on 2025-07-03 11:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doc", "0002_alter_act_author_alter_incomingletter_author_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="act",
            name="stamp",
            field=models.CharField(
                default="Без грифа", max_length=255, verbose_name="Гриф"
            ),
        ),
        migrations.AddField(
            model_name="act",
            name="type",
            field=models.CharField(
                default="Акт обыкновенный",
                help_text="(обязательное) Тип акта",
                max_length=255,
                verbose_name="Тип акта",
            ),
        ),
        migrations.AddField(
            model_name="memo",
            name="type",
            field=models.CharField(
                default="Не известно",
                help_text="(обязательное) Входящая/Исходящая",
                max_length=255,
                verbose_name="Тип служебной записки",
            ),
        ),
        migrations.AddField(
            model_name="organizations",
            name="addressee",
            field=models.TextField(
                default="Не указано",
                help_text="(не обязательно) Адрес организации, можно заполнить позже",
                verbose_name="Адрес организации",
            ),
        ),
        migrations.AddField(
            model_name="organizations",
            name="head",
            field=models.TextField(
                default="Не указано", verbose_name="Руководитель организации"
            ),
        ),
        migrations.AlterField(
            model_name="act",
            name="author",
            field=models.ForeignKey(
                auto_created=True,
                blank=True,
                editable=False,
                help_text="Создается автоматически",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_authors",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Автор записи",
            ),
        ),
        migrations.RemoveField(
            model_name="act",
            name="topic",
        ),
        migrations.AlterField(
            model_name="incomingletter",
            name="author",
            field=models.ForeignKey(
                auto_created=True,
                blank=True,
                editable=False,
                help_text="Создается автоматически",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_authors",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Автор записи",
            ),
        ),
        migrations.AlterField(
            model_name="memo",
            name="author",
            field=models.ForeignKey(
                auto_created=True,
                blank=True,
                editable=False,
                help_text="Создается автоматически",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_authors",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Автор записи",
            ),
        ),
        migrations.AlterField(
            model_name="memo",
            name="number",
            field=models.CharField(
                blank=True,
                help_text="(обязательное) Номер письма в нашей организации",
                max_length=255,
                null=True,
                verbose_name="Номер СЗ",
            ),
        ),
        migrations.AlterField(
            model_name="memo",
            name="self_date",
            field=models.DateField(
                blank=True,
                help_text="(не обязательно) Дата письма в нашей организации можно заполнить позже",
                null=True,
                verbose_name="Дата письма",
            ),
        ),
        migrations.AlterField(
            model_name="outgoingletter",
            name="author",
            field=models.ForeignKey(
                auto_created=True,
                blank=True,
                editable=False,
                help_text="Создается автоматически",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_authors",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Автор записи",
            ),
        ),
        migrations.AlterField(
            model_name="outgoingletter",
            name="outgoing_date",
            field=models.DateField(
                blank=True,
                help_text="(Не обязательно) Когда письмо было отправлено",
                null=True,
                verbose_name="Дата отправки",
            ),
        ),
        migrations.AddField(
            model_name="act",
            name="topic",
            field=models.CharField(
                default="Не указана",
                help_text="(обязательное) Тема акта",
                max_length=255,
                verbose_name="Тема акта",
            ),
        ),
    ]
