# Generated by Django 5.2.3 on 2025-06-26 13:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doc", "0002_disk_organizations_type_alter_letter_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="letter",
            name="type",
            field=models.ForeignKey(
                default=0,
                help_text="Акт, СЗ, Входящее...",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="letters",
                to="doc.type",
                verbose_name="Тип документа",
            ),
        ),
    ]
