# Generated by Django 5.2.3 on 2025-06-27 06:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doc", "0003_alter_letter_type"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="disk",
            options={
                "ordering": ["number"],
                "verbose_name": "Диск",
                "verbose_name_plural": "Диски",
            },
        ),
        migrations.AlterModelOptions(
            name="organizations",
            options={
                "ordering": ["name"],
                "verbose_name": "Организация",
                "verbose_name_plural": "Организации",
            },
        ),
        migrations.AlterModelOptions(
            name="type",
            options={
                "ordering": ["type"],
                "verbose_name": "Тип документа",
                "verbose_name_plural": "Типы документов",
            },
        ),
        migrations.CreateModel(
            name="Letters",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number",
                    models.CharField(max_length=255, verbose_name="Номер письма"),
                ),
                ("content", models.TextField(verbose_name="Содержание")),
                (
                    "send_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата отправки"
                    ),
                ),
                (
                    "addressee",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="doc.organizations",
                        verbose_name="Адресаты",
                    ),
                ),
                (
                    "disk",
                    models.OneToOneField(
                        help_text="Добавьте диск для записи через LPBurn",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="doc.disk",
                        verbose_name="Диск",
                    ),
                ),
                (
                    "type",
                    models.ForeignKey(
                        default=0,
                        help_text="Акт, СЗ, Входящее...",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="letter",
                        to="doc.type",
                        verbose_name="Тип документа",
                    ),
                ),
            ],
            options={
                "verbose_name": "Письмо",
                "verbose_name_plural": "Письма",
                "ordering": ["send_date"],
            },
        ),
        migrations.DeleteModel(
            name="Letter",
        ),
    ]
