# Generated by Django 5.2.3 on 2025-07-03 12:30

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("doc", "0003_act_stamp_act_type_memo_type_organizations_addressee_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="act",
            name="self_date",
            field=models.DateField(
                default=datetime.datetime(
                    2025, 7, 3, 12, 30, 31, 695818, tzinfo=datetime.timezone.utc
                ),
                help_text="(обязательное) Дата письма в нашей организации",
                verbose_name="Дата письма",
            ),
        ),
        migrations.AlterField(
            model_name="act",
            name="stamp",
            field=models.CharField(
                choices=[
                    ("Несекретно", "Несекретно"),
                    ("ДСП", "ДСП"),
                    ("Секретно", "Секретно"),
                    ("Совершенно секретно", "Совершенно секретно"),
                ],
                default="Без грифа",
                max_length=255,
                verbose_name="Гриф",
            ),
        ),
        migrations.AlterField(
            model_name="act",
            name="type",
            field=models.CharField(
                choices=[
                    ("О создании", "О создании"),
                    ("Об уничтожении", "Об уничтожении"),
                    ("О стирании", "О стирании"),
                ],
                default="О создании",
                help_text="(обязательное) Тип акта",
                max_length=255,
                verbose_name="Тип акта",
            ),
        ),
        migrations.AlterField(
            model_name="incomingletter",
            name="self_date",
            field=models.DateField(
                default=datetime.datetime(
                    2025, 7, 3, 12, 30, 31, 695818, tzinfo=datetime.timezone.utc
                ),
                help_text="(обязательное) Дата письма в нашей организации",
                verbose_name="Дата письма",
            ),
        ),
        migrations.AlterField(
            model_name="outgoingletter",
            name="self_date",
            field=models.DateField(
                default=datetime.datetime(
                    2025, 7, 3, 12, 30, 31, 695818, tzinfo=datetime.timezone.utc
                ),
                help_text="(обязательное) Дата письма в нашей организации",
                verbose_name="Дата письма",
            ),
        ),
        migrations.CreateModel(
            name="AttachedFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(blank=True, null=True, upload_to="attachments/"),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("object_id", models.PositiveIntegerField()),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
        ),
    ]
