# Generated by Django 5.2.3 on 2025-07-04 08:02

import datetime
import doc.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doc", "0004_alter_act_self_date_alter_act_stamp_alter_act_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="act",
            name="self_date",
            field=models.DateField(
                default=datetime.datetime(
                    2025, 7, 4, 8, 2, 9, 624705, tzinfo=datetime.timezone.utc
                ),
                help_text="(обязательное) Дата письма в нашей организации",
                verbose_name="Дата письма",
            ),
        ),
        migrations.AlterField(
            model_name="attachedfile",
            name="file",
            field=models.FileField(
                blank=True,
                help_text="Загрузите связанный файл",
                null=True,
                upload_to=doc.models.attachment_upload_path,
                verbose_name="Файл",
            ),
        ),
        migrations.RemoveField(
            model_name="incomingletter",
            name="answer_by",
        ),
        migrations.AlterField(
            model_name="incomingletter",
            name="self_date",
            field=models.DateField(
                default=datetime.datetime(
                    2025, 7, 4, 8, 2, 9, 624705, tzinfo=datetime.timezone.utc
                ),
                help_text="(обязательное) Дата письма в нашей организации",
                verbose_name="Дата письма",
            ),
        ),
        migrations.AlterField(
            model_name="incomingletter",
            name="sender_date",
            field=models.DateField(
                default=datetime.datetime(
                    2025, 7, 4, 8, 2, 9, 625705, tzinfo=datetime.timezone.utc
                ),
                help_text="(обязательное) Дата отправителя",
                verbose_name="Дата письма",
            ),
        ),
        migrations.AlterField(
            model_name="memo",
            name="number",
            field=models.CharField(
                blank=True,
                help_text="(не обязательно) Номер СЗ в нашей организации можно заполнить позже",
                max_length=255,
                null=True,
                verbose_name="Номер СЗ",
            ),
        ),
        migrations.AlterField(
            model_name="memo",
            name="self_date",
            field=models.DateField(
                blank=True,
                default=datetime.datetime(
                    2025, 7, 4, 8, 2, 9, 624705, tzinfo=datetime.timezone.utc
                ),
                help_text="(не обязательно) Дата СЗ в нашей организации можно заполнить позже",
                null=True,
                verbose_name="Дата СЗ",
            ),
        ),
        migrations.AlterField(
            model_name="memo",
            name="type",
            field=models.CharField(
                choices=[("Входящая", "Входящая"), ("Исходящая", "Исходящая")],
                default="Не известно",
                help_text="(обязательное) Входящая/Исходящая",
                max_length=255,
                verbose_name="Тип СЗ",
            ),
        ),
        migrations.AlterField(
            model_name="outgoingletter",
            name="self_date",
            field=models.DateField(
                default=datetime.datetime(
                    2025, 7, 4, 8, 2, 9, 624705, tzinfo=datetime.timezone.utc
                ),
                help_text="(обязательное) Дата письма в нашей организации",
                verbose_name="Дата письма",
            ),
        ),
        migrations.AddField(
            model_name="incomingletter",
            name="answer_by",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                to="doc.outgoingletter",
                verbose_name="Ответ на исх. письмо",
            ),
        ),
    ]
