# Generated by Django 5.2.3 on 2025-06-27 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doc", "0004_alter_disk_options_alter_organizations_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="letters",
            name="addressee",
        ),
        migrations.RemoveField(
            model_name="letters",
            name="disk",
        ),
        migrations.AlterField(
            model_name="letters",
            name="send_date",
            field=models.DateField(auto_now_add=True, verbose_name="Дата отправки"),
        ),
        migrations.AddField(
            model_name="letters",
            name="addressee",
            field=models.ManyToManyField(
                blank=True, to="doc.organizations", verbose_name="Адресаты"
            ),
        ),
        migrations.AddField(
            model_name="letters",
            name="disk",
            field=models.ManyToManyField(
                blank=True,
                help_text="Добавьте диск для записи через LPBurn",
                to="doc.disk",
                verbose_name="Диск",
            ),
        ),
    ]
