# Generated by Django 5.2.3 on 2025-07-04 08:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doc", "0005_alter_act_self_date_alter_attachedfile_file_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="act",
            name="self_date",
            field=models.DateField(
                default=datetime.datetime(
                    2025, 7, 4, 8, 8, 6, 822189, tzinfo=datetime.timezone.utc
                ),
                help_text="(обязательное) Дата письма в нашей организации",
                verbose_name="Дата письма",
            ),
        ),
        migrations.AlterField(
            model_name="incomingletter",
            name="self_date",
            field=models.DateField(
                default=datetime.datetime(
                    2025, 7, 4, 8, 8, 6, 822189, tzinfo=datetime.timezone.utc
                ),
                help_text="(обязательное) Дата письма в нашей организации",
                verbose_name="Дата письма",
            ),
        ),
        migrations.AlterField(
            model_name="incomingletter",
            name="sender_date",
            field=models.DateField(
                default=datetime.datetime(
                    2025, 7, 4, 8, 8, 6, 824189, tzinfo=datetime.timezone.utc
                ),
                help_text="(обязательное) Дата отправителя",
                verbose_name="Дата письма",
            ),
        ),
        migrations.AlterField(
            model_name="memo",
            name="self_date",
            field=models.DateField(
                blank=True,
                default=datetime.datetime(
                    2025, 7, 4, 8, 8, 6, 822189, tzinfo=datetime.timezone.utc
                ),
                help_text="(не обязательно) Дата СЗ в нашей организации можно заполнить позже",
                null=True,
                verbose_name="Дата СЗ",
            ),
        ),
        migrations.RemoveField(
            model_name="outgoingletter",
            name="answer_by",
        ),
        migrations.AlterField(
            model_name="outgoingletter",
            name="self_date",
            field=models.DateField(
                default=datetime.datetime(
                    2025, 7, 4, 8, 8, 6, 822189, tzinfo=datetime.timezone.utc
                ),
                help_text="(обязательное) Дата письма в нашей организации",
                verbose_name="Дата письма",
            ),
        ),
        migrations.AddField(
            model_name="outgoingletter",
            name="answer_by",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                to="doc.incomingletter",
                verbose_name="Ответ на вх. письмо",
            ),
        ),
    ]
