# Generated by Django 5.2.3 on 2025-06-27 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doc", "0005_remove_letters_addressee_remove_letters_disk_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Okr",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField(verbose_name="Название ОКР")),
            ],
            options={
                "verbose_name": "Окр",
                "verbose_name_plural": "Окр",
                "ordering": ["name"],
            },
        ),
    ]
