# Generated by Django 5.2.3 on 2025-06-27 08:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doc", "0006_okr"),
    ]

    operations = [
        migrations.AddField(
            model_name="letters",
            name="okr",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="doc.okr",
                verbose_name="ОКР",
            ),
        ),
    ]
