# Generated by Django 5.2.3 on 2025-06-30 07:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doc", "0007_letters_okr"),
    ]

    operations = [
        migrations.CreateModel(
            name="Peoples",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        auto_created=True,
                        max_length=255,
                        verbose_name="Имя поьзователя",
                    ),
                ),
            ],
            options={
                "verbose_name": "Автор",
                "verbose_name_plural": "Авторы",
                "ordering": ["name"],
            },
        ),
        migrations.AlterField(
            model_name="letters",
            name="addressee",
            field=models.ManyToManyField(
                blank=True,
                help_text="(обязательное)",
                to="doc.organizations",
                verbose_name="Адресаты",
            ),
        ),
        migrations.AlterField(
            model_name="letters",
            name="content",
            field=models.TextField(
                help_text="(обязательное)", verbose_name="Содержание"
            ),
        ),
        migrations.AlterField(
            model_name="letters",
            name="disk",
            field=models.ManyToManyField(
                blank=True,
                help_text="(не обязательное) Добавьте новый диск для записи через LPBurn. ",
                to="doc.disk",
                verbose_name="Диск",
            ),
        ),
        migrations.AlterField(
            model_name="letters",
            name="number",
            field=models.CharField(
                help_text="(обязательное)", max_length=255, verbose_name="Номер письма"
            ),
        ),
        migrations.AlterField(
            model_name="letters",
            name="okr",
            field=models.ForeignKey(
                help_text="(не обязательное)",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="doc.okr",
                verbose_name="ОКР",
            ),
        ),
        migrations.AlterField(
            model_name="letters",
            name="send_date",
            field=models.DateField(
                auto_now_add=True,
                help_text="(обязательное)",
                verbose_name="Дата отправки",
            ),
        ),
        migrations.AlterField(
            model_name="letters",
            name="type",
            field=models.ForeignKey(
                default=0,
                help_text="(обязательное)",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="letter",
                to="doc.type",
                verbose_name="Тип документа",
            ),
        ),
    ]
