# Generated by Django 5.2.3 on 2025-07-04 12:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doc", "0007_incomingletter_info_alter_act_self_date_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="outgoingletter",
            name="answer_by",
        ),
        migrations.AddField(
            model_name="outgoingletter",
            name="answers_to",
            field=models.ManyToManyField(
                blank=True,
                related_name="answered_by_outgoing",
                to="doc.incomingletter",
                verbose_name="Ответ на вх. письмо",
            ),
        ),
        migrations.AlterField(
            model_name="act",
            name="self_date",
            field=models.DateField(
                default=datetime.datetime(
                    2025, 7, 4, 12, 54, 8, 52825, tzinfo=datetime.timezone.utc
                ),
                help_text="(обязательное) Дата письма в нашей организации",
                verbose_name="Дата письма",
            ),
        ),
        migrations.AlterField(
            model_name="incomingletter",
            name="answer_by",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="incoming_letters",
                to="doc.outgoingletter",
                verbose_name="Ответ на исх. письмо",
            ),
        ),
        migrations.AlterField(
            model_name="incomingletter",
            name="info",
            field=models.TextField(
                blank=True, null=True, verbose_name="Информация об исполнителях"
            ),
        ),
        migrations.AlterField(
            model_name="incomingletter",
            name="self_date",
            field=models.DateField(
                default=datetime.datetime(
                    2025, 7, 4, 12, 54, 8, 52825, tzinfo=datetime.timezone.utc
                ),
                help_text="(обязательное) Дата письма в нашей организации",
                verbose_name="Дата письма",
            ),
        ),
        migrations.AlterField(
            model_name="incomingletter",
            name="sender_date",
            field=models.DateField(
                default=datetime.datetime(
                    2025, 7, 4, 12, 54, 8, 55825, tzinfo=datetime.timezone.utc
                ),
                help_text="(обязательное) Дата отправителя",
                verbose_name="Дата письма",
            ),
        ),
        migrations.AlterField(
            model_name="memo",
            name="self_date",
            field=models.DateField(
                blank=True,
                default=datetime.datetime(
                    2025, 7, 4, 12, 54, 8, 52825, tzinfo=datetime.timezone.utc
                ),
                help_text="(не обязательно) Дата СЗ в нашей организации можно заполнить позже",
                null=True,
                verbose_name="Дата СЗ",
            ),
        ),
        migrations.AlterField(
            model_name="outgoingletter",
            name="self_date",
            field=models.DateField(
                default=datetime.datetime(
                    2025, 7, 4, 12, 54, 8, 52825, tzinfo=datetime.timezone.utc
                ),
                help_text="(обязательное) Дата письма в нашей организации",
                verbose_name="Дата письма",
            ),
        ),
    ]
