# Generated by Django 5.2.3 on 2025-06-30 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doc", "0008_peoples_alter_letters_addressee_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="letters",
            name="author",
            field=models.CharField(
                default="0",
                help_text="Автор документа",
                max_length=64,
                null=True,
                verbose_name="Автор",
            ),
        ),
        migrations.AlterField(
            model_name="peoples",
            name="name",
            field=models.CharField(
                auto_created=True, max_length=255, verbose_name="Чей"
            ),
        ),
    ]
