# Generated by Django 5.2.3 on 2025-06-30 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doc", "0009_letters_author_alter_peoples_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="letters",
            name="author",
            field=models.CharField(
                default="0",
                editable=False,
                help_text="Автор документа",
                max_length=64,
                null=True,
                verbose_name="Чей",
            ),
        ),
    ]
