# Generated by Django 5.2.3 on 2025-06-30 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doc", "0010_alter_letters_author"),
    ]

    operations = [
        migrations.AlterField(
            model_name="letters",
            name="disk",
            field=models.ManyToManyField(
                blank=True,
                default="Нет диска",
                help_text="(не обязательное) Добавьте новый диск для записи через LPBurn. ",
                to="doc.disk",
                verbose_name="Диск",
            ),
        ),
    ]
