# Generated by Django 5.2.3 on 2025-07-09 08:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doc", "0011_alter_act_self_date_alter_incomingletter_self_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="act",
            name="сreated_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 7, 9, 8, 3, 9, 758954, tzinfo=datetime.timezone.utc
                ),
                editable=False,
                help_text="(обязательное) Дата создания записи",
                verbose_name="Дата создания",
            ),
        ),
        migrations.AddField(
            model_name="incomingletter",
            name="сreated_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 7, 9, 8, 3, 9, 758954, tzinfo=datetime.timezone.utc
                ),
                editable=False,
                help_text="(обязательное) Дата создания записи",
                verbose_name="Дата создания",
            ),
        ),
        migrations.AddField(
            model_name="memo",
            name="сreated_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 7, 9, 8, 3, 9, 758954, tzinfo=datetime.timezone.utc
                ),
                editable=False,
                help_text="(обязательное) Дата создания записи",
                verbose_name="Дата создания",
            ),
        ),
        migrations.AddField(
            model_name="outgoingletter",
            name="сreated_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 7, 9, 8, 3, 9, 758954, tzinfo=datetime.timezone.utc
                ),
                editable=False,
                help_text="(обязательное) Дата создания записи",
                verbose_name="Дата создания",
            ),
        ),
        migrations.AlterField(
            model_name="act",
            name="self_date",
            field=models.DateField(
                default=datetime.datetime(
                    2025, 7, 9, 8, 3, 9, 758954, tzinfo=datetime.timezone.utc
                ),
                help_text="(обязательное) Дата письма в нашей организации",
                verbose_name="Дата письма",
            ),
        ),
        migrations.AlterField(
            model_name="incomingletter",
            name="self_date",
            field=models.DateField(
                default=datetime.datetime(
                    2025, 7, 9, 8, 3, 9, 758954, tzinfo=datetime.timezone.utc
                ),
                help_text="(обязательное) Дата письма в нашей организации",
                verbose_name="Дата письма",
            ),
        ),
        migrations.AlterField(
            model_name="incomingletter",
            name="sender_date",
            field=models.DateField(
                default=datetime.datetime(
                    2025, 7, 9, 8, 3, 9, 768955, tzinfo=datetime.timezone.utc
                ),
                help_text="(обязательное) Дата отправителя",
                verbose_name="Дата письма",
            ),
        ),
        migrations.AlterField(
            model_name="outgoingletter",
            name="self_date",
            field=models.DateField(
                default=datetime.datetime(
                    2025, 7, 9, 8, 3, 9, 758954, tzinfo=datetime.timezone.utc
                ),
                help_text="(обязательное) Дата письма в нашей организации",
                verbose_name="Дата письма",
            ),
        ),
    ]
