# Generated by Django 5.2.3 on 2025-07-09 08:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doc", "0012_act_сreated_at_incomingletter_сreated_at_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="act",
            name="сreated_at",
        ),
        migrations.RemoveField(
            model_name="incomingletter",
            name="сreated_at",
        ),
        migrations.RemoveField(
            model_name="memo",
            name="сreated_at",
        ),
        migrations.RemoveField(
            model_name="outgoingletter",
            name="сreated_at",
        ),
        migrations.AddField(
            model_name="act",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 7, 9, 8, 11, 51, 800791, tzinfo=datetime.timezone.utc
                ),
                editable=False,
                help_text="(обязательное) Дата создания записи",
                verbose_name="Дата создания",
            ),
        ),
        migrations.AddField(
            model_name="incomingletter",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 7, 9, 8, 11, 51, 800791, tzinfo=datetime.timezone.utc
                ),
                editable=False,
                help_text="(обязательное) Дата создания записи",
                verbose_name="Дата создания",
            ),
        ),
        migrations.AddField(
            model_name="memo",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 7, 9, 8, 11, 51, 800791, tzinfo=datetime.timezone.utc
                ),
                editable=False,
                help_text="(обязательное) Дата создания записи",
                verbose_name="Дата создания",
            ),
        ),
        migrations.AddField(
            model_name="outgoingletter",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 7, 9, 8, 11, 51, 800791, tzinfo=datetime.timezone.utc
                ),
                editable=False,
                help_text="(обязательное) Дата создания записи",
                verbose_name="Дата создания",
            ),
        ),
        migrations.AlterField(
            model_name="act",
            name="self_date",
            field=models.DateField(
                default=datetime.datetime(
                    2025, 7, 9, 8, 11, 51, 800791, tzinfo=datetime.timezone.utc
                ),
                help_text="(обязательное) Дата письма в нашей организации",
                verbose_name="Дата письма",
            ),
        ),
        migrations.AlterField(
            model_name="incomingletter",
            name="self_date",
            field=models.DateField(
                default=datetime.datetime(
                    2025, 7, 9, 8, 11, 51, 800791, tzinfo=datetime.timezone.utc
                ),
                help_text="(обязательное) Дата письма в нашей организации",
                verbose_name="Дата письма",
            ),
        ),
        migrations.AlterField(
            model_name="incomingletter",
            name="sender_date",
            field=models.DateField(
                default=datetime.datetime(
                    2025, 7, 9, 8, 11, 51, 810791, tzinfo=datetime.timezone.utc
                ),
                help_text="(обязательное) Дата отправителя",
                verbose_name="Дата письма",
            ),
        ),
        migrations.AlterField(
            model_name="outgoingletter",
            name="self_date",
            field=models.DateField(
                default=datetime.datetime(
                    2025, 7, 9, 8, 11, 51, 800791, tzinfo=datetime.timezone.utc
                ),
                help_text="(обязательное) Дата письма в нашей организации",
                verbose_name="Дата письма",
            ),
        ),
    ]
