# Generated by Django 5.2.3 on 2025-06-30 13:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doc", "0012_alter_letters_okr"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="letters",
            name="workers",
            field=models.ManyToManyField(
                to=settings.AUTH_USER_MODEL, verbose_name="Кому отписано"
            ),
        ),
        migrations.AlterField(
            model_name="letters",
            name="disk",
            field=models.ManyToManyField(
                default="Нет диска",
                help_text="(не обязательное) Добавьте новый диск для записи через LPBurn. ",
                to="doc.disk",
                verbose_name="Диск",
            ),
        ),
        migrations.AlterField(
            model_name="letters",
            name="okr",
            field=models.ForeignKey(
                default=0,
                help_text="(не обязательное)",
                on_delete=django.db.models.deletion.PROTECT,
                to="doc.okr",
                verbose_name="ОКР",
            ),
        ),
    ]
