# Generated by Django 5.2.3 on 2025-07-09 10:32

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doc", "0013_remove_act_сreated_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="act",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                editable=False,
                help_text="(обязательное) Дата создания записи",
                verbose_name="Дата создания",
            ),
        ),
        migrations.AlterField(
            model_name="act",
            name="self_date",
            field=models.DateField(
                default=datetime.datetime(
                    2025, 7, 9, 10, 32, 44, 75374, tzinfo=datetime.timezone.utc
                ),
                help_text="(обязательное) Дата письма в нашей организации",
                verbose_name="Дата письма",
            ),
        ),
        migrations.RemoveField(
            model_name="act",
            name="topic",
        ),
        migrations.AlterField(
            model_name="incomingletter",
            name="addressee",
            field=models.ForeignKey(
                help_text="(обязательное) Организация, от которой пришло письмо",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="doc.organizations",
                verbose_name="От кого",
            ),
        ),
        migrations.AlterField(
            model_name="incomingletter",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                editable=False,
                help_text="(обязательное) Дата создания записи",
                verbose_name="Дата создания",
            ),
        ),
        migrations.AlterField(
            model_name="incomingletter",
            name="self_date",
            field=models.DateField(
                default=datetime.datetime(
                    2025, 7, 9, 10, 32, 44, 75374, tzinfo=datetime.timezone.utc
                ),
                help_text="(обязательное) Дата письма в нашей организации",
                verbose_name="Дата письма",
            ),
        ),
        migrations.AlterField(
            model_name="incomingletter",
            name="sender_date",
            field=models.DateField(
                default=datetime.datetime(
                    2025, 7, 9, 10, 32, 44, 86374, tzinfo=datetime.timezone.utc
                ),
                help_text="(обязательное) Дата отправителя",
                verbose_name="Дата письма отправителя",
            ),
        ),
        migrations.AlterField(
            model_name="memo",
            name="addressee",
            field=models.ManyToManyField(
                blank=True,
                help_text="(обязательное) Кому адресована служебная записка",
                to="doc.organizations",
                verbose_name="Кому",
            ),
        ),
        migrations.AlterField(
            model_name="memo",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                editable=False,
                help_text="(обязательное) Дата создания записи",
                verbose_name="Дата создания",
            ),
        ),
        migrations.AlterField(
            model_name="outgoingletter",
            name="addressee",
            field=models.ManyToManyField(
                blank=True,
                help_text="(обязательное) Кому адресовано исходящее письмо",
                to="doc.organizations",
                verbose_name="Кому",
            ),
        ),
        migrations.AlterField(
            model_name="outgoingletter",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                editable=False,
                help_text="(обязательное) Дата создания записи",
                verbose_name="Дата создания",
            ),
        ),
        migrations.AlterField(
            model_name="outgoingletter",
            name="self_date",
            field=models.DateField(
                default=django.utils.timezone.now,
                help_text="(обязательное) Дата взятия номера в нашей организации",
                verbose_name="Дата взятия номера",
            ),
        ),
        migrations.AddField(
            model_name="act",
            name="topic",
            field=models.ManyToManyField(
                to="doc.topics", verbose_name="Тема документа"
            ),
        ),
    ]
