# Generated by Django 5.2.3 on 2025-06-30 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doc", "0013_letters_workers_alter_letters_disk_alter_letters_okr"),
    ]

    operations = [
        migrations.AlterField(
            model_name="letters",
            name="okr",
            field=models.ForeignKey(
                default=None,
                help_text="(не обязательное)",
                on_delete=django.db.models.deletion.PROTECT,
                to="doc.okr",
                verbose_name="ОКР",
            ),
        ),
    ]
