# Generated by Django 5.2.3 on 2025-07-09 10:42

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doc", "0014_alter_act_created_at_alter_act_self_date_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="act",
            name="self_date",
            field=models.DateField(
                default=datetime.datetime(
                    2025, 7, 9, 10, 42, 54, 109773, tzinfo=datetime.timezone.utc
                ),
                help_text="(обязательное) Дата письма в нашей организации",
                verbose_name="Дата письма",
            ),
        ),
        migrations.AlterField(
            model_name="incomingletter",
            name="self_date",
            field=models.DateField(
                default=datetime.datetime(
                    2025, 7, 9, 10, 42, 54, 109773, tzinfo=datetime.timezone.utc
                ),
                help_text="(обязательное) Дата письма в нашей организации",
                verbose_name="Дата письма",
            ),
        ),
        migrations.AlterField(
            model_name="incomingletter",
            name="sender_date",
            field=models.DateField(
                default=datetime.datetime(
                    2025, 7, 9, 10, 42, 54, 119773, tzinfo=datetime.timezone.utc
                ),
                help_text="(обязательное) Дата отправителя",
                verbose_name="Дата письма отправителя",
            ),
        ),
        migrations.AddConstraint(
            model_name="act",
            constraint=models.UniqueConstraint(
                fields=("number", "self_date"), name="unique_number_self_date_act"
            ),
        ),
        migrations.AddConstraint(
            model_name="incomingletter",
            constraint=models.UniqueConstraint(
                fields=("number", "self_date"),
                name="unique_number_self_date_incoming_letter",
            ),
        ),
        migrations.AddConstraint(
            model_name="memo",
            constraint=models.UniqueConstraint(
                fields=("number", "self_date"), name="unique_number_self_date_memo"
            ),
        ),
        migrations.AddConstraint(
            model_name="outgoingletter",
            constraint=models.UniqueConstraint(
                fields=("number", "self_date"),
                name="unique_number_self_date_outgoing_letter",
            ),
        ),
    ]
