# Generated by Django 5.2.3 on 2025-06-30 13:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doc", "0015_alter_letters_disk"),
    ]

    operations = [
        migrations.AlterField(
            model_name="letters",
            name="okr",
            field=models.ForeignKey(
                default=None,
                help_text="(не обязательное)",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="doc.okr",
                verbose_name="ОКР",
            ),
        ),
    ]
