# Generated by Django 5.2.3 on 2025-06-30 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("doc", "0016_alter_letters_okr"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="letters",
            name="workers",
        ),
    ]
