# Generated by Django 5.2.3 on 2025-06-30 13:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doc", "0017_remove_letters_workers"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="letters",
            name="workers",
            field=models.ManyToManyField(
                to=settings.AUTH_USER_MODEL, verbose_name="Кому отписано"
            ),
        ),
    ]
