# Generated by Django 5.2.3 on 2025-07-01 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doc", "0018_letters_workers"),
    ]

    operations = [
        migrations.AlterField(
            model_name="peoples",
            name="name",
            field=models.CharField(
                auto_created=True, max_length=255, verbose_name="Автор записи"
            ),
        ),
    ]
