# Generated by Django 5.2.3 on 2025-07-01 11:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doc", "0020_alter_letters_workers"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="letters",
            name="author",
            field=models.CharField(
                default="0",
                editable=False,
                help_text="Создается автоматически",
                max_length=64,
                null=True,
                verbose_name="Автор записи",
            ),
        ),
        migrations.AlterField(
            model_name="letters",
            name="okr",
            field=models.ForeignKey(
                blank=True,
                default=None,
                help_text="(не обязательное)",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="doc.okr",
                verbose_name="ОКР",
            ),
        ),
        migrations.AlterField(
            model_name="letters",
            name="send_date",
            field=models.DateField(
                help_text="(обязательное) Добавьте от какого числа письмо",
                verbose_name="Дата отправки",
            ),
        ),
        migrations.AlterField(
            model_name="letters",
            name="workers",
            field=models.ManyToManyField(
                blank=True,
                help_text="(не обязательное) Добавьте исполнителей письма",
                null=True,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Исполнители",
            ),
        ),
        migrations.AddConstraint(
            model_name="letters",
            constraint=models.UniqueConstraint(
                fields=("number", "send_date"), name="unique_number_date"
            ),
        ),
    ]
