# Generated by Django 5.2.3 on 2025-07-01 11:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doc", "0021_alter_letters_author_alter_letters_okr_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="letters",
            name="unique_number_date",
        ),
        migrations.AddConstraint(
            model_name="letters",
            constraint=models.UniqueConstraint(
                fields=("number", "send_date"), name="unique_number_send_date"
            ),
        ),
    ]
