# Generated by Django 5.2.3 on 2025-07-01 11:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doc", "0022_remove_letters_unique_number_date_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="letters",
            name="workers",
            field=models.ManyToManyField(
                blank=True,
                help_text="(не обязательное) Добавьте исполнителей письма",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Исполнители",
            ),
        ),
    ]
